## Problem: Dealer Sales Analysis with NumPy

### You are analyzing monthly sales data from a dealership. The dataset shows how many units of each product category were sold over 6 months.

In [1]:
import numpy as np

# Rows = Product categories (ATVs, Motorcycles, Side-by-Sides, Personal Watercraft)
# Columns = Months (Jan → Jun)
sales = np.array([
    [15, 18, 20, 22, 25, 28],   # ATVs
    [10, 12, 13, 15, 18, 20],   # Motorcycles
    [8,  9,  11, 14, 16, 19],   # Side-by-Sides
    [5,  7,  9,  12, 14, 16]    # PWCs
])

### Tasks:

Slice out March data (all product categories, column for March).

Find total sales per product category (sum along months).

Find total sales per month (sum along categories).

Calculate the average monthly sales for Motorcycles.

Which category sold the most overall? (return both name + total units).

Apply a 10% growth projection for July (broadcast a multiplier).

Find the month with the highest overall sales.

In [4]:
march_data = sales[:, 2]
print(march_data)

[20 13 11  9]


In [6]:
total_sales_per_category = np.sum(sales, axis=1)
print(total_sales_per_category)

[128  88  77  63]


In [7]:
total_sales_per_month = np.sum(sales, axis=0)
print(total_sales_per_month)

[38 46 53 63 73 83]


In [8]:
average_motorcycle_sales = np.mean(sales[1, :])
print(average_motorcycle_sales)

14.666666666666666


In [10]:
most_sales_index = np.argmax(total_sales_per_category)
categories = ["ATVs", "Motorcycles", "Side-by-Sides", "PWCs"]
most_sales_categories = categories[most_sales_index]
print(most_sales_categories, total_sales_per_category[most_sales_index])

ATVs 128


In [11]:
july_projection = sales * 1.10
print(july_projection)

[[16.5 19.8 22.  24.2 27.5 30.8]
 [11.  13.2 14.3 16.5 19.8 22. ]
 [ 8.8  9.9 12.1 15.4 17.6 20.9]
 [ 5.5  7.7  9.9 13.2 15.4 17.6]]


In [12]:
highest_sales_month_index = np.argmax(total_sales_per_month)
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
highest_sales_month = months[highest_sales_month_index]
print(highest_sales_month, total_sales_per_month[highest_sales_month_index])

Jun 83
